### ISSUE TITLE
Dependency check & Mac compatibility issue

### ISSUE THREAD

**Issue by vitalii-vm** [Turbots/tap-on-h2o#4]
When i ran the scripts for the very first time on Mac (m1), i got the following errors
1. yq is missing
loadSetting:1: command not found: yq
/and yes, the script is not failing and just tries to continue/

2. kubectx is missing (no, it's not a developer's system)

3. wget is missing

|INFO    | Downloading and install Kubectl vSphere plugin
install_vsphere_plugin:4: command not found: wget
mkdir: /home/vscode: Operation not supported
unzip:  cannot find or open downloads/vsphere-plugin.zip, downloads/vsphere-plugin.zip.zip or downloads/vsphere-plugin.zip.ZIP.
mv: rename downloads/bin to /home/vscode/.local: No such file or directory

So finally it stops at

|INFO    | Provisioning workload clusters in Supervisor Cluster 
error: flag needs an argument: 'n' in -n

**Comment by rhjensen79** [comment]
I will add the required packaged to the base image. 
You will need to do a "rebuild image", in vscode, for the changes to take effect-

**Comment by rhjensen79** [comment]
After a rebuild i now get :

yq --version
yq (https://github.com/mikefarah/yq/) version v4.30.5

kubectx --help
USAGE:
  kubectx                       : list the contexts
  kubectx <NAME>                : switch to context <NAME>
  kubectx -                     : switch to the previous context
  kubectx -c, --current         : show the current context name
  kubectx <NEW_NAME>=<NAME>     : rename context <NAME> to <NEW_NAME>
  kubectx <NEW_NAME>=.          : rename current-context to <NEW_NAME>
  kubectx -d <NAME> [<NAME...>] : delete context <NAME> ('.' for current-context)
                                  (this command won't delete the user/cluster entry
                                  that is used by the context)
  kubectx -u, --unset           : unset the current context

  kubectx -h,--help             : show this message
  
  wget --version
GNU Wget 1.21.2 built on linux-gnu.

I found an error on the download of the vSphere plugin. fixing that next

**Comment by rhjensen79** [comment]
Fixed and working.
